myblog/blog/urls.py
from django.urls import path
from . import views
from django.urls import path
from .views import log_to_file, PostListCreateView

urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name='addcomments'),
               path('<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
               path('<int:pk>/del_likes/', views.DelLike.as_view(), name='del_likes'),
               path('log/', log_to_file, name='log_to_file'),
               path('api/posts/', PostListCreateView.as_view(), name='post-list-create')]                   #Cоздаем списк где будут все пути для наших url

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))               #Указываем путь до нашего файла urls из blog
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/blog/models.py
from django.db import models

class Post(models.Model):        #обращаемся к родительному классу Model, чтобы наследовать настройки
    '''данные о посте'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст запсии')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')
    def __str__(self):         #Отображаем в списке модели в админ панели
        return f'{self.title}, {self.author}'

    class Meta:                 #Создаем класс для определения различных вещей о модели
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

class Comments(models.Model):              #Создаем класс для комментов
    '''Комментарий'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)    #Связываем две таблицы

    def __str__(self):         #Отображаем в списке модели в админ панели
        return f'{self.name}, {self.post}'

    class Meta:                 #Создаем класс для определения различных вещей о модели
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

class Likes(models.Model):
    '''лайки'''
    ip = models.CharField('ip-adres', max_length=100)
    pos = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.http import HttpResponseServerError, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Post, Likes
from .form import CommentsForm
from rest_framework import generics
from .serializers import PostSerializer
import logging

logger = logging.getLogger(__name__)

@csrf_exempt
def log_to_file(request):
    if request.method == 'POST':
        try:
            data = request.POST
            log_level = data.get('level', 'INFO')
            log_message = data.get('message', '')

            # Определите уровень логирования в соответствии с вашими требованиями
            if log_level == 'INFO':
                logger.info(log_message)
            elif log_level == 'ERROR':
                logger.error(log_message)
            else:
                logger.debug(log_message)

            return JsonResponse({'status': 'success'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

class PostView(View):
    '''вывод записей'''

    def get(self, request):
        try:
            posts = Post.objects.all()  # ссылаемся на всю информацию из нашей таблицы
            return render(request, 'blog/blog.html', {'post_list': posts})
        except Exception as e:
            # Обработка ошибок при выполнении запроса к базе данных
            error_message = f'An error occurred while fetching posts: {str(e)}'
            return HttpResponseServerError(error_message)

class PostDetail(View):
    '''отдельная страница записи'''
    def get(self, request, pk):             #получаем id конкретной записи
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post' : post})

class AddComments(View):
    '''Добавление комментариев'''
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():                  #проверяем валидность
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')

def get_client_ip(request):
    x_forward_for = request.META.get('HTTP_X_FORWARDED_FOR')   #Храним ip-адрес клиента
    if x_forward_for:
        ip = x_forward_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
        return ip

class AddLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip=ip_client, pos_id=pk)
            return redirect(f'/{pk}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.pos_id = int(pk)
            new_like.save()
            return redirect(f'/{pk}')

class DelLike(View):
    def get(self, request, pk):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client)
            lik.delete()
            return redirect(f'/{pk}')
        except:
            return redirect(f'/{pk}')

class PostListCreateView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

myblog/templates/blog/blog.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
	<title>Hat-News.kz</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">

	<link rel="shortcut icon" href="css/images/favicon.ico">

</head>
<body>
<div class="shell">
	<div class="border">



		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>Записи</h3>
					{% for post in post_list %}
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ post.img.url }}" width="200px"></a>
						</div>
						<div class="text left">
							<h4><a href="{{ post.id }}"> {{ post.title }}</a></h4>
							<p>{{ post.description }}</p>
							<p><strong>Автор:</strong>  {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
					{% endfor %}
				</div>
			</div>

			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright ©  2023 </p>
	</div>
</div>

</body>
<script type="text/javascript">

    var logger = {
        log: function (message) {
            console.log(message);  // Выводим сообщение в консоль браузера
            // Также можно отправить сообщение на сервер или использовать другие методы логирования
        }
    };

    // Пример использования логирования
    logger.log("Страница загружена успешно.");
</script>

<!-- Логирование на стороне сервера -->
<script type="text/javascript">
    // Отправляем запрос на сервер для логирования
    fetch('/log/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            level: 'INFO',
            message: 'Страница загружена успешно.',
        }),
    });
</script>
</html>

myblog/templates/blog/blog_detail.html
{% load static %}
<html>
<head>
	<title>Hat-News.kz</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">

	<link rel="shortcut icon" href="css/images/favicon.ico">

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>

			</ul>
		</div>

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ post.title }}</h3>
                  <p align="center">
                    <img src="{{ post.img.url }}" width="50%">
                  </p>

					<div class="item">
						<div class="text left">
							<p>{{ post.description }}</p>
							<p><strong>Автор:</strong>  {{ post.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>

				</div>
			</div>
			<div>
				{% for comment in post.comments_set.all %}
				<div class="view_comment">
					<h4>{{ comment.name }}</h4>
					<p>
						{{ comment.text_comments }}
					</p>
				</div>
				{% endfor %}
			</div>

			<div class="cl">&nbsp;</div>
		</div>
		<div>
			<br>
			<p>Понравилось: {{ post.likes_set.all.count }}</p>
			<br>
			<a href="{% url 'add_likes' post.id %}">Like</a>
			<a href="{% url 'del_likes' post.id %}">Dislike</a>
		</div>
		<div class="form-comment">
			<h3>Оставить комментарий</h3>
			<div>
				<form action="{% url 'addcomments' post.id %}" method="post">
					{% csrf_token %}
					<div>
						<label>Ваш комментарий</label>
						<textarea name="text_comments"></textarea>
					</div>
					<div>
						<label>Ваше имя *</label>
						<input type="text" name="name">
					</div>
					<div>
						<label>Ваше email *</label>
						<input type="email" name="email">
					</div>
					<div><input type="submit"></div>
				</form>
			</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright ©  2023 </p>
	</div>
</div>

</body></html>